### ISSUE TITLE
Unable to use bulk write

### ISSUE THREAD

**Issue by deepujain** [paulgoldbaum/scala-influxdb-client#10]
<dependency>
            <groupId>com.paulgoldbaum</groupId>
            <artifactId>scala-influxdb-client_2.11</artifactId>
            <version>0.4.3</version>
        </dependency>

Number of points: 
points:5169

Error:

Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.$conforms()Lscala/Predef$$less$colon$less;
    at com.paulgoldbaum.influxdbclient.Database.buildWriteParameters(Database.scala:52)
    at com.paulgoldbaum.influxdbclient.Database.executeWrite(Database.scala:32)
    at com.paulgoldbaum.influxdbclient.Database.bulkWrite(Database.scala:28)

**Comment by deepujain** [comment]
def postToInflux(points: List[Point], influxDBHost: String, influxDBPort: Integer, influxDBName: String) = {
    val influxdb = InfluxDB.connect(influxDBHost, influxDBPort)
    val database = influxdb.selectDatabase(influxDBName)
    val result = database.bulkWrite(points, precision = Precision.MILLISECONDS)
    if (!Await.result(result, 2.minutes)) {

```
}
```

  }

**Comment by deepujain** [comment]
Influx DB Version : 0.10

**Comment by deepujain** [comment]
The exception is resolved after using  2.10 v of library.

<dependency>
            <groupId>com.paulgoldbaum</groupId>
            <artifactId>scala-influxdb-client_2.10</artifactId>
            <version>0.4.3</version>
        </dependency>

I use scala 2.10.3.

Exception is resolved , However now i see that Await.result(result, 2.minutes))  returns but 
1. Data is not seen on influx db (show series does not show anything)
2. The client process never completes

<img width="493" alt="screen shot 2016-03-06 at 7 23 26 pm" src="https://cloud.githubusercontent.com/assets/406777/13560143/ee90641c-e3d0-11e5-900a-5de7e202d1ab.png">

**Comment by deepujain** [comment]
Got it working:

import java.text.SimpleDateFormat
import java.util.Date

import scala.concurrent.ExecutionContext.Implicits.global
import scala.util.Failure
import scala.util.Success

import com.nicta.scoobi.Scoobi.fromTextFile
import com.paulgoldbaum.influxdbclient.InfluxDB
import com.paulgoldbaum.influxdbclient.Parameter.Precision
import com.paulgoldbaum.influxdbclient.Point

  def postToInflux(points: List[Point], influxDBHost: String, influxDBPort: Integer, influxDBName: String) = {
    val influxdb = InfluxDB.connect(influxDBHost, influxDBPort)
    val database = influxdb.selectDatabase(influxDBName)
    val future = database.bulkWrite(points, precision = Precision.MILLISECONDS)
    future onComplete {
      case Success(result) => {
        println("Write to influxDB:" + result)
        influxdb.close()
      }
      case Failure(t) => {
        println("An error has occured: " + t.getMessage)
        influxdb.close()
      }
    }
  }
