### ISSUE TITLE
Unable to submit data to InfluxDB

### ISSUE THREAD

**Issue by deepujain** [paulgoldbaum/scala-influxdb-client#12]
Error:
Exception in thread "main" java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.headers()Lorg/jboss/netty/handler/codec/http/HttpHeaders;
    at com.ning.http.client.providers.netty.request.NettyRequestFactory.newNettyRequest(NettyRequestFactory.java:178)
    at com.ning.http.client.providers.netty.request.NettyRequestSender.newNettyRequestAndResponseFuture(NettyRequestSender.java:181)
    at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:135)
    at com.ning.http.client.providers.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:117)
    at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:87)
    at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:506)
    at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:225)
    at com.paulgoldbaum.influxdbclient.HttpClient.makeRequest(HttpClient.scala:49)
    at com.paulgoldbaum.influxdbclient.HttpClient.post(HttpClient.scala:41)
    at com.paulgoldbaum.influxdbclient.Database.executeWrite(Database.scala:34)
    at com.paulgoldbaum.influxdbclient.Database.bulkWrite(Database.scala:28)
    at com.ebay.gps.monitoring.DataPoster.postToInflux(DataPoster.scala:28)
    at com.ebay.gps.monitoring.DataPoster.postData(DataPoster.scala:22)
    at com.ebay.gps.monitoring.PostDataRunner$.postData(PostDataRunner.scala:22)
    at com.ebay.gps.monitoring.PostDataRunner$.main(PostDataRunner.scala:31)
    at com.ebay.gps.monitoring.PostDataRunner.main(PostDataRunner.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

<scala.version>2.10.4</scala.version>
<scala.tools.version>2.10</scala.tools.version>

<dependency>
            <groupId>com.paulgoldbaum</groupId>
            <artifactId>scala-influxdb-client_2.10</artifactId>
            <version>0.4.3</version>
        </dependency>

Works fine on Eclipse but fails when run from Command Line.

My FAT JAR contains

$ jar -tvf ingestion-service/target/ep-job.jar 
     0 Mon Mar 07 16:46:38 PST 2016 META-INF/
   104 Mon Mar 07 16:46:36 PST 2016 META-INF/MANIFEST.MF
     0 Mon Mar 07 16:46:38 PST 2016 lib/
3461506 Wed Jun 17 15:48:18 PDT 2015 lib/scoobi_2.10-0.9.2.jar
14445780 Wed Jun 17 15:34:44 PDT 2015 lib/scala-compiler-2.10.4.jar
7126372 Wed Jun 17 15:34:10 PDT 2015 lib/scala-library-2.10.4.jar
3206180 Thu Jan 21 10:52:48 PST 2016 lib/scala-reflect-2.10.6.jar
303139 Wed Jun 17 15:35:18 PDT 2015 lib/avro-1.7.4.jar
 29555 Wed Jun 17 15:34:40 PDT 2015 lib/paranamer-2.3.jar
538830 Wed Jun 17 15:48:14 PDT 2015 lib/xstream-1.4.8.jar
  7188 Wed Jun 17 15:48:12 PDT 2015 lib/xmlpull-1.1.3.1.jar
 24956 Wed Jun 17 15:48:12 PDT 2015 lib/xpp3_min-1.1.4c.jar
644148 Wed Jun 17 15:48:14 PDT 2015 lib/javassist-3.12.1.GA.jar
809342 Wed Jun 17 15:48:16 PDT 2015 lib/kiama_2.10-1.6.0.jar
1648200 Wed Jun 17 15:48:22 PDT 2015 lib/guava-11.0.2.jar
 19353 Wed Jun 17 15:48:14 PDT 2015 lib/dsinfo_2.10-0.3.0.jar
 74708 Wed Jun 17 15:48:14 PDT 2015 lib/dsprofile_2.10-0.3.0.jar
530654 Sun Mar 06 20:46:46 PST 2016 lib/scallop_2.10-0.9.5.jar
208781 Wed Jun 17 15:48:14 PDT 2015 lib/jline-2.11.jar
2047799 Wed Jun 17 15:48:16 PDT 2015 lib/shapeless_2.10.4-2.0.0.jar
 11965 Wed Jun 17 15:48:14 PDT 2015 lib/scoobi-compatibility-hadoop2_2.10-1.0.3.jar
433368 Wed Jun 17 15:48:16 PDT 2015 lib/httpclient-4.2.5.jar
227275 Wed Jun 17 15:48:16 PDT 2015 lib/httpcore-4.2.4.jar
1330395 Fri Feb 12 16:58:02 PST 2016 lib/netty-3.10.4.Final.jar
166584 Wed Jun 17 15:48:22 PDT 2015 lib/avro-mapred-1.7.4-hadoop2.jar
187840 Wed Jun 17 15:48:22 PDT 2015 lib/avro-ipc-1.7.4.jar
449505 Wed Jun 17 15:34:42 PDT 2015 lib/velocity-1.7.jar
134133 Wed Jun 17 15:34:42 PDT 2015 lib/servlet-api-2.5-20081211.jar
266688 Wed Jun 17 15:48:22 PDT 2015 lib/avro-ipc-1.7.4-tests.jar
217053 Wed Jun 17 15:48:16 PDT 2015 lib/libthrift-0.9.1.jar
315805 Wed Jun 17 15:36:46 PDT 2015 lib/commons-lang3-3.1.jar
9398321 Wed Jun 17 15:46:56 PDT 2015 lib/scalaz-core_2.10-7.1.0.jar
716873 Wed Jun 17 15:48:18 PDT 2015 lib/scalaz-iteratee_2.10-7.1.0.jar
428107 Wed Jun 17 15:46:44 PDT 2015 lib/scalaz-effect_2.10-7.1.0.jar
349162 Wed Jun 17 15:46:42 PDT 2015 lib/scalaz-concurrent_2.10-7.1.0.jar
588962 Wed Jun 17 15:48:18 PDT 2015 lib/scalaz-scalacheck-binding_2.10-7.1.0.jar
376007 Wed Jun 17 15:48:18 PDT 2015 lib/scalaz-typelevel_2.10-7.1.0.jar
715291 Wed Jun 17 15:48:18 PDT 2015 lib/scalaz-xml_2.10-7.1.0.jar
872327 Wed Sep 02 00:31:30 PDT 2015 lib/scalacheck_2.10-1.11.4.jar
 14755 Wed Jun 17 15:46:44 PDT 2015 lib/test-interface-1.0.jar
3478319 Sun Feb 28 17:00:08 PST 2016 lib/platform-scoobi_2.10-1.0-20160226.163738-103.jar
7350967 Sun Feb 28 17:00:18 PST 2016 lib/platform_2.10-1.0-20160226.163139-110.jar
121394 Sun Feb 28 17:00:18 PST 2016 lib/platform-macros_2.10-1.0-20160226.162947-109.jar
720704 Wed Jun 17 15:34:28 PDT 2015 lib/quasiquotes_2.10-2.0.1.jar
487652 Sun Feb 28 16:58:46 PST 2016 lib/sojourner-common-0.2.0-hadoop-2.4.1-EBAY-2.jar
194480 Mon Aug 31 16:27:42 PDT 2015 lib/nscala-time_2.10-2.2.0.jar
621992 Sun Feb 28 16:58:42 PST 2016 lib/joda-time-2.8.2.jar
 38460 Wed Jun 17 15:48:24 PDT 2015 lib/joda-convert-1.2.jar
146396 Sun Mar 06 19:12:52 PST 2016 lib/scala-influxdb-client_2.10-0.4.3.jar
740350 Thu Mar 03 14:59:36 PST 2016 lib/async-http-client-1.9.31.jar
289719 Sun Mar 06 19:12:54 PST 2016 lib/spray-json_2.10-1.3.2.jar
 25593 Mon Mar 07 16:46:34 PST 2016 lib/ingestion-service-0.0.1-SNAPSHOT.jar

Am i missing something ?

**Comment by deepujain** [comment]
$ mvn dependency:tree | grep netty
[INFO] |  +- io.netty:netty:jar:3.10.4.Final:compile

INFO] +- com.paulgoldbaum:scala-influxdb-client_2.10:jar:0.4.3:compile
[INFO] |  +- com.ning:async-http-client:jar:1.9.31:compile
[INFO] |  +- io.netty:netty:jar:3.10.4.Final:compile
[INFO] |  - io.spray:spray-json_2.10:jar:1.3.2:compile
[

Is this the right version of netty ?

**Comment by deepujain** [comment]
HttpRequest httpRequest;
    NettyRequest nettyRequest;
    if ((body instanceof NettyDirectBody))
    {
      ChannelBuffer buffer = ((NettyDirectBody)NettyDirectBody.class.cast(body)).channelBuffer();
      HttpRequest httpRequest = new DefaultHttpRequest(httpVersion, method, requestUri);

```
  httpRequest.setContent(buffer);
  nettyRequest = new NettyRequest(httpRequest, null);
}
else
{
  httpRequest = new DefaultHttpRequest(httpVersion, method, requestUri);
  nettyRequest = new NettyRequest(httpRequest, body);
}
HttpHeaders headers = httpRequest.headers();  ==> ERROR
```

HttpRequest extends HttpMessage and that contains headers() API.
Implementation: DefaultHttpRequest extends DefaultHttpMessage and that contains headers() API

  public HttpHeaders headers()
  {
    return this.headers;
  }

What is going wrong here ?

**Comment by deepujain** [comment]
An older version of netty was interfering while running the code using hadoop command. Now using java with my jar (hence latest netty) before the rest of hadoop classpath solved that error.

But i see this
case Failure(t) => {
        println("An error has occured: " + t.getMessage)
        influxdb.close()
      }

How do i get the exact error ? or more details ?

**Comment by deepujain** [comment]
[http] 2016/03/08 01:19:53 10.103.178.197 - - [08/Mar/2016:01:19:53 -0700] POST /write?db=testDB&precision=n HTTP/1.1 404 43 - AHC/1.0 88ef3cf4-e506-11e5-9ae7-000000000000 20.241757ms

Logged in influxDB

**Comment by deepujain** [comment]
REsolved. db did not exists

**Comment by deepujain** [comment]
I see a data ingestion issue now. Opening a new ticket.
