### ISSUE TITLE
tag should not be empty string

### ISSUE THREAD

**Issue by da-liii** [paulgoldbaum/scala-influxdb-client#24]
If the tag is assigned an empty string, it only throws an exception saying the return code is 400 and fails to write the point. I think it should be more informative.

Below is how influxdb java client handle empty tag string.
``` java
class InfluxDBTest {
  @Test
  def testEmptyStringTag = {
    val influxDB = InfluxDBFactory.connect("http://localhost:8086", "admin", "admin")

    val point1 = Point.measurement("hello")
      .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
      .tag("a", "")
      .addField("v", 13f)
      .build()

    influxDB.write("test", "default", point1)
  }
}

java.lang.RuntimeException: {"error":"unable to parse 'hello,a= v=13.0 1479448317053000000': missing tag value"}


	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:266)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:167)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:157)
	at samples.InfluxDBTest.testEmptyStringTag(InfluxDBTest.scala:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by paulgoldbaum** [comment]
Fixed in 3bf1f737e1635601bd8d657fa4ea26650e7df40d

Thanks for the report @sadhen!
