### ISSUE TITLE
Bulkwrite doesn't persist data

### ISSUE THREAD

**Issue by juanarmentia** [paulgoldbaum/scala-influxdb-client#35]
Hello!

I want to persist data in InfluxDB database. Storing point by point, the process is correct, but using bulkwrite for storing a list of points the process returns the following error:

`com.paulgoldbaum.influxdbclient.UnknownErrorException: Error during write: An error occurred during the request
	at com.paulgoldbaum.influxdbclient.Database.exceptionFromStatusCode(Database.scala:65)
	at com.paulgoldbaum.influxdbclient.Database$$anonfun$executeWrite$1.applyOrElse(Database.scala:36)
	at com.paulgoldbaum.influxdbclient.Database$$anonfun$executeWrite$1.applyOrElse(Database.scala:36)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.paulgoldbaum.influxdbclient.HttpException: An error occurred during the request
	at com.paulgoldbaum.influxdbclient.HttpClient$ResponseHandler.onThrowable(HttpClient.scala:83)
	at org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:278)
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:181)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:237)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.ConnectException: executor not accepting a task
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	... 26 more
Caused by: java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:60)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
	... 18 more
`

Does anyone know how to solve it?

Thanks in advanced!

**Comment by Claus1** [comment]
Console based app which reproduces the error?

**Comment by juanarmentia** [comment]
Yes, the terminal of Ubuntu

**Comment by Claus1** [comment]
code?

**Comment by juanarmentia** [comment]
val influxdb = InfluxDB.connect("localhost", 8086)
 val db = influxdb.selectDatabase("sourceDB")

val points = List(
      Point("test_measurement1").addField("value1", 123),
      Point("test_measurement2").addField("value2", 123),
      Point("test_measurement3").addField("value3", 123)
    )

val future = db.bulkWrite(points, precision = Precision.MILLISECONDS)

future onComplete {
    case Success(result) => {
        println("Write to influxDB:" + result)
    }
    case Failure(t) => {
        println("An error has occured: " + t.getMessage + "\n" + t.printStackTrace())
    }
}

**Comment by Claus1** [comment]
![image](https://user-images.githubusercontent.com/1247062/48745483-32702b80-ec9e-11e8-96d9-24b140aff1b9.png)

**Comment by juanarmentia** [comment]
Thanks! I noticed that I was closing influxdb instance before future complete. It runs OK.
